#!/usr/bin/env python3
"""
decode_primes.py — decoder for the prime dataset (primes_1T.bin)

FORMAT
------
The dataset uses LEB128 varint gap encoding.  Each prime is stored as the
difference (gap) from the previous prime, encoded as a variable-length integer:

  - If the gap fits in 7 bits (<= 127), it takes 1 byte.
  - Each byte stores 7 bits of the value; the high bit (0x80) means "more
    bytes follow".  This is the standard LEB128 unsigned format.

Near 1 trillion the average prime gap is ~28, so almost every prime costs
exactly one byte.  The full 37.6-billion-prime dataset fits in ~37.8 GB (35.2 GiB).

USAGE
-----
  # print all primes (very large output — pipe to head or a file)
  python decode_primes.py primes_1T.bin | head -20

  # count and show largest without printing everything
  python decode_primes.py primes_1T.bin --count

  # extract the first N primes (e.g. all primes under 1 billion)
  python decode_primes.py primes_1T.bin --head 50847534 > primes_1B.txt

  # verify against a known value: pi(10^7) = 664,579
  python decode_primes.py primes_1T.bin --head 664579 --count

ABOUT THE DATASET
-----------------
All prime numbers from 2 through 999,999,999,989 (the largest prime under
one trillion).  Generated by a proprietary engine developed by BeltUp LLC;
the engine implementation is not disclosed.  Only the dataset and this
decoder are published here.

  Primes found : 37,607,912,018
  Largest prime: 999,999,999,989
  File size    : ~37.8 GB / 35.2 GiB  (binary gap format)
  Format       : LEB128 unsigned varint gaps, no header, no padding

KNOWN VALIDATION POINTS
-----------------------
  pi(10^6)  =        78,498   (count of primes <= 1,000,000)
  pi(10^7)  =       664,579   (count of primes <= 10,000,000)
  pi(10^8)  =     5,761,455   (count of primes <= 100,000,000)
  pi(10^9)  =    50,847,534   (count of primes <= 1,000,000,000)
  pi(10^12) = 37,607,912,018  (count of primes <= 1,000,000,000,000)
"""

import sys
import argparse


def decode(path: str):
    """Stream primes from a LEB128 gap-encoded binary file."""
    prev = 0
    gap, shift = 0, 0  # must persist across chunk boundaries — a varint can straddle two chunks
    with open(path, 'rb') as f:
        while True:
            chunk = f.read(1 << 20)  # 1 MB at a time
            if not chunk:
                break
            for b in chunk:
                gap |= (b & 0x7F) << shift
                if not (b & 0x80):
                    prev += gap
                    yield prev
                    gap = shift = 0
                else:
                    shift += 7


def main():
    parser = argparse.ArgumentParser(
        description='Decode a LEB128 gap-encoded prime dataset.')
    parser.add_argument('file', help='Path to primes_1T.bin (or any .bin chunk)')
    parser.add_argument('--head', type=int, default=0,
                        metavar='N', help='Stop after the first N primes')
    parser.add_argument('--count', action='store_true',
                        help='Print count and largest prime instead of each value')
    args = parser.parse_args()

    count = 0
    largest = 0

    for prime in decode(args.file):
        count += 1
        largest = prime

        if not args.count:
            print(prime)

        if args.head and count >= args.head:
            break

    if args.count:
        print(f'count   : {count:,}')
        print(f'largest : {largest:,}')


if __name__ == '__main__':
    main()
